name: Test
on:
  push:
  pull_request:
jobs:
  full:
    name: Node.js 18 Full
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
        env:
          FORCE_COLOR: 2
  short:
    runs-on: ubuntu-latest
    strategy:
      node: [14, 16]
    name: Node.js ${{ matrix.node }} Quick
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm run unit
        env:
          FORCE_COLOR: 2
